name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login (GitHub)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./images/${{ inputs.name }}
          file: ./images/${{ inputs.name }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ inputs.name }}:${{ inputs.tag }}
